### ISSUE TITLE
Hardcoded font path failure

### ISSUE THREAD

**Issue by ACodingfreak** [cobblau/RFC2Kindle#1]
OS: Centos7
# ./rfc2kindle.py -i rfc7379.txt

Unable to find font: /usr/share/cups/fonts/Courier
Convert IETF RFC TXT file to HTML for kindlegen
-h --help    This message
-i --input   input file
Traceback (most recent call last):
  File "./rfc2kindle.py", line 219, in <module>
    main()
  File "./rfc2kindle.py", line 104, in main
    usage()
  File "./rfc2kindle.py", line 22, in usage
    print "-f --font    font file to use for monospace images (default:%s)" % defaultfont
NameError: global name 'defaultfont' is not defined

**Comment by marauderlabs** [comment]
Same on Debian.
`cat /etc/debian_version`
`8.4`

After fixing `NameError: global name 'defaultfont' is not defined`

**Comment by eproxus** [comment]
This seems to be a bug on line 22: https://github.com/cobblau/RFC2Kindle/blob/master/rfc2kindle.py#L22

If you change it to `default_font` it works (given that you use the `-f` argument on platforms where the default font doesn't exist).
